name: Laravel Exists Without Soft Deleted Rule CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json
      run: composer validate

    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Run linting
      run: composer run-script check-style

    - name: Run static analysis
      run: composer run-script stan

    - name: Run test suite
      run: COMPOSER_PROCESS_TIMEOUT=600 composer run-script test
